export const getProducts = () => {
  return [
    {
      id: 1,
      name: "'67 Ford Fairlane",
      image: "/prods/ford.jpg",
      price: 789,
      category: "Scale Cars",
      inventoryStatus: "OUTOFSTOCK",
      description: `This collector's item meets the highest standards currently demanded by slot car enthusiasts. It features a finely and authentically printed driver's figure, with each figure individually painted to match the specific vehicle. The car is compatible with all commercial track systems and comes fully assembled. Additionally, it is presented on a removable display base, protected by a clear acrylic dust cover, ensuring both functionality and elegant display.`,
      rating: 4.7,
      brand: "XYZ Cars",
      availabilityDate: "01/09/2024",
      link: "https://prod1.xyz",
    },
    {
      id: 2,
      name: "Digital Hand Controller",
      image: "/prods/remote.jpg",
      price: 549,
      category: "Scale Track",
      inventoryStatus: "INSTOCK",
      description: `This hand controller is suitable for use with Scalextric Digital Powerbases. Not suitable for use with standard Scalextric or older analogue power bases.`,
      rating: 4.3,
      brand: "XYZ Tracks",
      availabilityDate: "02/09/2024",
      link: "https://prod2.xyz",
    },
    {
      id: 3,
      name: "Brush Barrels",
      image: "/prods/barrels.jpg",
      price: 149,
      category: "Scale Parts",
      inventoryStatus: "INSTOCK",
      description: `Tyco chassis use brushes to make contact with the armature to allow it to turn. Though not often, there are times when the brush barrel(s) overheats and hits its melting point. This results in the requirement to replace the barrel that houses the brush.`,
      rating: 4.9,
      brand: "XYZ Parts",
      availabilityDate: "03/09/2024",
      link: "https://prod4.xyz",
    },
    {
      id: 4,
      name: "Aston Martin DB5",
      image: "/prods/aston.jpg",
      price: 1149,
      category: "Scale Cars",
      inventoryStatus: "INSTOCK",
      description: `An Aston Martin DB5 is not a regular sight at racetracks around the world. But in the 2019 AMOC series Martin Stephenson bucked that trend. This magnificently coloured White Gold DB5 has raced in the series for a number of years, and certainly brings some glamour to the racetrack whenever it appears.`,
      rating: 4.1,
      brand: "XYZ Cars",
      availabilityDate: "04/09/2024",
      link: "https://prod5.xyz",
    },
    {
      id: 5,
      name: "Oversized Crystal Case",
      image: "/prods/clearcase.jpg",
      price: 299,
      category: "Display Cases",
      inventoryStatus: "LOWSTOCK",
      description: `1:18 oversized scale diecast case with crystal clear clarity. This 1:18 oversized scale diecast case also works upright and it’s a great Barbie™ doll display case or a bobble head doll display case. The retail box includes three cut-out background images allowing you to create your own diorama effect. Those images include a MODERN CAR GARAGE great for NASCAR™ or Drag Cars, a CLASSIC CAR GARAGE SCENE great for older style cars, and a NEON SIGNS background.`,
      rating: 4.5,
      brand: "XYZ Cases",
      availabilityDate: "05/09/2024",
      link: "https://prod6.xyz",
    },
    {
      id: 6,
      name: "Pick-Up Shoe Springs",
      image: "/prods/pickup.jpg",
      price: 49,
      category: "Scale Parts",
      inventoryStatus: "OUTOFSTOCK",
      description: `The 440-X2 pick-up shoe springs produced by Tyco work just as well on Mattel chassis. They are used to keep tension on the pick-up shoes in order for them to stay on the rails. This results in more power being transferred to the chassis. You'll want to keep spares of these since their size makes them difficult to find if dropped.`,
      rating: 3.8,
      brand: "XYZ Parts",
      availabilityDate: "06/09/2024",
      link: "https://prod7.xyz",
    },
    {
      id: 7,
      name: "1989 Batmobile",
      image: "/prods/batmobile.jpg",
      price: 1749,
      category: "Scale Cars",
      inventoryStatus: "LOWSTOCK",
      description: `The 1989 Batmobile is equipped with a range of advanced features, including Spark Plug compatibility and Digital Plug readiness, making it adaptable to various systems. Its high-definition design is enhanced by Magnatraction, providing superior grip on the track. The Batmobile also boasts flashing lights, working rear lights, and functioning headlights, adding to its authenticity. Additionally, it comes with an easy-change guide blade, allowing for quick and effortless maintenance.`,
      rating: 4.4,
      brand: "XYZ Cars",
      availabilityDate: "07/09/2024",
      link: "https://prod8.xyz",
    },
    {
      id: 8,
      name: "Audi R8 HH Police Car",
      image: "/prods/police.jpg",
      price: 999,
      category: "Scale Cars",
      inventoryStatus: "INSTOCK",
      description: `While not your average police car, the Audi R8 is surely something not many criminals would be able to escape from! This Scalextric version comes complete with both a siren and flashing police lights on the roof. Perfect for any aspiring law enforcement officer to test their mettle!`,
      rating: 4.1,
      brand: "XYZ Cars",
      availabilityDate: "08/09/2024",
      link: "https://prod9.xyz",
    },
    {
      id: 9,
      name: "Billet T Boss",
      image: "/prods/tboss.jpg",
      price: 89,
      category: "Scale Parts",
      inventoryStatus: "INSTOCK",
      description: `Billet Delrin T boss for all slot cars. This T boss replaces worn and wobbly stock gear bosses. The precision CNC machined T boss keeps gear mesh true and consistent resulting in faster lap times, Less wear and tear and cooler running temps.`,
      rating: 4.2,
      brand: "XYZ Parts",
      availabilityDate: "09/09/2024",
      link: "https://prod10.xyz",
    },
    {
      id: 10,
      name: `9" CrossOver Straight Track`,
      image: "/prods/track.jpg",
      price: 249,
      category: "Scale Track",
      inventoryStatus: "OUTOFSTOCK",
      description: `With the 9" Cross Over track straight pieces you won't be able to run side-by-side. Look out! Don't get knocked off! Simply add them to your existing layout for additional fun.`,
      rating: 4.2,
      brand: "XYZ Tracks",
      availabilityDate: "10/09/2024",
      link: "https://prod11.xyz",
    },
  ];
};
